name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build Backend
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker build -t ${DOCKER_USERNAME}/isitempty-backend:latest .
        docker push ${DOCKER_USERNAME}/isitempty-backend:latest
        
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        debug: true
        script: |
          cd /var/www/isitempty
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "SEOUL_KEY=${{ secrets.SEOUL_KEY }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "APP_AUTH_TOKEN_SECRET=${{ secrets.APP_AUTH_TOKEN_SECRET }}" >> .env
          echo "APP_AUTH_TOKEN_EXPIRY=${{ secrets.APP_AUTH_TOKEN_EXPIRY }}" >> .env
          echo "APP_AUTH_REFRESH_TOKEN_EXPIRY=${{ secrets.APP_AUTH_REFRESH_TOKEN_EXPIRY }}" >> .env

          echo "SSH_HOST=" >> .env
          echo "SSH_PORT=" >> .env
          echo "SSH_USERNAME=" >> .env
          echo "SSH_PASSWORD=" >> .env
          echo "SSH_REMOTE_HOST=" >> .env
          echo "SSH_REMOTE_PORT=" >> .env
          echo "SSH_LOCAL_PORT=" >> .env
          
          docker-compose pull backend
          docker stop isitempty-backend || true
          docker rm -f isitempty-backend || true
          docker-compose up -d --no-deps --force-recreate backend
          
          sleep 10
          docker-compose ps
          docker image prune -af --filter "until=24h"